### ISSUE TITLE
OffscreenRenderer failed.

### ISSUE THREAD

**Issue by ChenXuelinCXL** [mmatl/pyrender#3]
Hi @mmatl , after I finished the steps needed for offscreen render, I ran the example script, and I got this, do you have any clue for the reason? Thanks!

FYI, I am using docker, ubuntu 16, a headless server connected over SSH.

root@dffaaaba9cf1:/workspace/mesh_render# PYOPENGL_PLATFORM=osmesa python meshrender_example.py 
No handlers could be found for logger "OpenGL.acceleratesupport"
Traceback (most recent call last):
  File "meshrender_example.py", line 136, in <module>
    r = OffscreenRenderer(viewport_width=640*2, viewport_height=480*2)
  File "/usr/local/lib/python2.7/dist-packages/pyrender/offscreen.py", line 28, in __init__
    self._create()
  File "/usr/local/lib/python2.7/dist-packages/pyrender/offscreen.py", line 102, in _create
    self._platform.make_current()
  File "/usr/local/lib/python2.7/dist-packages/pyrender/platforms.py", line 216, in make_current
    self.viewport_width, self.viewport_height))
AssertionError

**Comment by ChenXuelinCXL** [comment]
@mmatl ,  sorry for asking that stupid question and thanks for sharing this wonder code, now I have successfully made it work!

Just for your information, after I installed pyrender via pip, it seems like there is no 'shaders' folder under in the installation, which trigered a 'No such file' error in running time. So I just downloaded the shaders folder from github repo and copied it to the desired place, and now it is working.

**Comment by mmatl** [comment]
@ChenXuelinCXL There are no stupid questions! I probably just forgot to include the 'shaders' folder in the pip repo. Will double-check that ASAP and fix it. Thanks for the heads up!

**Comment by mmatl** [comment]
Should be fixed with https://github.com/mmatl/pyrender/commit/9a11d4c4fb6291e9644edd8474a9c05529fd9120

**Comment by mmatl** [comment]
And it's fixed in version 0.1.6, now on PyPi. Thanks @ChenXuelinCXL for the solution.

**Comment by wolterlw** [comment]
Still having this issue with version 0.1.32
```
     42         assert(OSMesaMakeCurrent(
     43             self._context, self._buffer, gl.GL_UNSIGNED_BYTE,
---> 44             self.viewport_width, self.viewport_height
     45         ))
     46 

AssertionError: 
```
Interestingly enough this only happens when I try to run the script in Jupyter. If called from the command line - everything works as expected.

**Comment by lucivpav** [comment]
I am experiencing the same problem. Version 0.1.39.

**Comment by lucivpav** [comment]
My problem was probably causes by the fact that I originally compiled OSMesa v18.0.0 from source, not following the [instructions](https://pyrender.readthedocs.io/en/latest/install/index.html#building-from-source). Installing the (recommended?) version OSMesa v18.3.3 fixed the problem for me. Don't forget to update the environment variables, so they do not contain a path to the former mesa directory.

**Comment by tegusi** [comment]
In my case, simply running
```
apt-get upgrade
```
solve the problem. Maybe it is related to the gcc version?

**Comment by barvin04** [comment]
@mmatl 
The "Assertion Error" is still there with PyOpenGL(3.1.5) and Pyrender(0.1.45) during OffScreen rendering

**Comment by jinfagang** [comment]
@barvin04 I can confirm problem still exist during OffScreen rendering.

the error are:

```
pyrender/platforms/osmesa.py", line 42, in make_current
    assert(OSMesaMakeCurrent(
AssertionError
```

**Comment by jinfagang** [comment]
Even got it when set egl as backend
